/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package transaction;

import static java.lang.Integer.parseInt;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fahim
 */
public class give_tax_id extends javax.swing.JFrame {

    /**
     * Creates new form give_tax_id
     */
    public give_tax_id() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        year = new datechooser.beans.DateChooserPanel();
        jLabel1 = new javax.swing.JLabel();
        citizen_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tax_genarate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tax_history = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CHOOSE YEAR");

        citizen_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizen_idActionPerformed(evt);
            }
        });

        jLabel2.setText("CITIZEN ID");

        tax_genarate.setText("TAX GENARATE");
        tax_genarate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tax_genarateActionPerformed(evt);
            }
        });

        tax_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tax_id", "tax year", "total amount", "transaction time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tax_history);

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tax_genarate, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(citizen_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(citizen_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(tax_genarate, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void citizen_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizen_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citizen_idActionPerformed

    private void tax_genarateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tax_genarateActionPerformed
        // TODO add your handling code here:
        Connection con=null;
            Statement stmt = null;
            con=connection.getconnection();
            CallableStatement cs = null;
            DefaultTableModel model = (DefaultTableModel)tax_history.getModel();
            
             if(citizen_id.getText().equals(""))
             {
                  JOptionPane.showMessageDialog(null,"Enter all appropriate fields");
             }
             else
             {
                 try
                 {
                 
                 int id=parseInt(citizen_id.getText());
                 
                 //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                 String tax_year = new SimpleDateFormat("yyyy").format(year.getSelectedDate().getTime());
                 int foo = Integer.parseInt(tax_year);
                 foo=foo+1;
                 tax_year=tax_year+"-12-31";
                 String current_date=String.valueOf(foo);
                 current_date=current_date+"-01-01";
                 
                  System.out.println(current_date );
                 System.out.println(tax_year );
                 
                  java.sql.Date date1 =java.sql.Date.valueOf(current_date);
                  java.sql.Date date2 =java.sql.Date.valueOf(tax_year);
                 
                   System.out.println(id);
                 System.out.println(date1);
                 System.out.println(date2);
                  
                    String q="{call yearly_tax(?,?,?)}";
                 cs=con.prepareCall(q);
                 cs.setInt(1,id);
                 cs.setDate(2,date1);
                 cs.setDate(3,date2);
            
                 cs.executeUpdate();  
                 
                 
                 
                Statement state = con.createStatement();
                
                String query= String.format("Select tax_trans_id,tax_year,transaction_tax,tax_trans_time"
                        + " from tax_transaction where citizen_id='%d'",id);
                
                 
                ResultSet rs=state.executeQuery(query); 
                model.setRowCount(0);
                while(rs.next()){
                    
                                  
                  String trans_id=rs.getString("tax_trans_id");
                    String t_year=rs.getString("tax_year");
                    Date trans_time=rs.getDate("tax_trans_time");
                 Double amount =rs.getDouble("transaction_tax");
                    
                   model.addRow(new Object[]{trans_id,t_year,amount,trans_time});

                 
                }
              rs.close();
             
                 }
                 catch (SQLException e) {
 
			System.out.println(e.getMessage());
 
		}
                 
             }
        
        
        
    }//GEN-LAST:event_tax_genarateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
            
            this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(give_tax_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(give_tax_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(give_tax_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(give_tax_id.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new give_tax_id().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField citizen_id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tax_genarate;
    private javax.swing.JTable tax_history;
    private datechooser.beans.DateChooserPanel year;
    // End of variables declaration//GEN-END:variables
}
